services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./logs/db:/var/log/postgresql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5432:5432"

  app:
    image: ghcr.io/bwl-andromeda/webapp:latest
    container_name: webapp
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./logs/app:/logs
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
