services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./logs/db:/var/log/postgresql
    ports:
      - "5432:5432"

  app:
    image: ghcr.io/bwl-andromeda/webapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapp
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./logs/app:/logs
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
