name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Login and Build and publish
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "DOCKER_TAG: ${{ env.DOCKER_TAG }}"
          docker build . --file Dockerfile --tag ${{ env.DOCKER_TAG }}
          docker push ${{ env.DOCKER_TAG }}