name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
    - name: 'Log in to registry'
      uses: docker/login-action
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Build and Push the Docker image'
      run: |
        docker build . --file Dockerfile --tag ghcr.io/bwl-andromeda/webapp:$(date +%s)
        docker push ghcr.io/bwl-andromeda/webapp:$(date +%s)
  