name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@main

    - uses: docker/login-action
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag webapp:$(date +%s)

    - name: Push the Docker image
      run: docker push ghcr.io/bwl-andromeda/webapp:$(date +%s)