name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    env:
      DOCKER_TAG: ghcr.io/${{ github.actor }}/webapp:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Login and Build and publish
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build . --file Dockerfile --tag ${{ env.DOCKER_TAG }}
          docker push ${{ env.DOCKER_TAG }}

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: install ssh keys
  #       run: |
  #         mkdir -p ~/.ssh
  #         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
  #         chmod 600 ~/.ssh/id_rsa
  #         ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
  #     - name: copy docker compose config
  #       run: scp docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:docker-compose.yml
  #     - name: connect and pull
  #       run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker-compose pull && docker-compose up -d && exit"
  #     - name: cleanup config
  #       if: always()
  #       run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm docker-compose.yml"
  #     - name: cleanup keys
  #       if: always()
  #       run: rm -rf ~/.ssh docker-compose-secret.yml